# generated by wxGlade 0.6.8 on Fri Sep 04 05:24:13 2015
#
# To get wxPerl visit http://wxPerl.sourceforge.net/
#

use Wx 0.15 qw[:allclasses];
use strict;
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

package DPOPanelInfo;

use Wx qw[:everything];
use base qw(Wx::Panel);
use strict;


sub new {
    my( $self, $parent, $id, $pos, $size, $style, $name ) = @_;
    $parent = undef              unless defined $parent;
    $id     = -1                 unless defined $id;
    $pos    = wxDefaultPosition  unless defined $pos;
    $size   = wxDefaultSize      unless defined $size;
    $name   = ""                 unless defined $name;

    # begin wxGlade: DPOPanelInfo::new
    $style = wxTAB_TRAVERSAL 
        unless defined $style;

    $self = $self->SUPER::new( $parent, $id, $pos, $size, $style, $name );

    $self->__set_properties();
    $self->__do_layout();

    # end wxGlade
    return $self;

}


sub __set_properties {
    my $self = shift;
    # begin wxGlade: DPOPanelInfo::__set_properties
    return;
    # end wxGlade
}

sub __do_layout {
    my $self = shift;
    # begin wxGlade: DPOPanelInfo::__do_layout
    $self->{sizer_4} = Wx::BoxSizer->new(wxHORIZONTAL);
    $self->SetSizer($self->{sizer_4});
    $self->{sizer_4}->Fit($self);
    # end wxGlade
}

# end of class DPOPanelInfo

1;

