// -*- C++ -*-
//
// generated by wxGlade 0.6.8 on Mon Nov 16 10:49:45 2015
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef XYZFRAME_H
#define XYZFRAME_H

#include <wx/wx.h>
#include <wx/image.h>
#include "wx/intl.h"

#ifndef APP_CATALOG
#define APP_CATALOG "app"  // replace with the appropriate catalog name
#endif


// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class XyzFrame: public wxFrame {
public:
    // begin wxGlade: XyzFrame::ids
    // end wxGlade

    XyzFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: XyzFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: XyzFrame::attributes
    wxButton* button_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    virtual void on_button_1(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // XYZFRAME_H
