// -*- C++ -*-
//
// generated by wxGlade 0.6.8 on Mon Nov 16 10:49:45 2015
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#include <wx/wx.h>
#include "XyzFrame.h"

// begin wxGlade: ::extracode
// end wxGlade


XyzFrame::XyzFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: XyzFrame::XyzFrame
    button_1 = new wxButton(this, wxID_ANY, _("button_1"));

    set_properties();
    do_layout();
    // end wxGlade
}


void XyzFrame::set_properties()
{
    // begin wxGlade: XyzFrame::set_properties
    SetTitle(_("frame_1"));
    // end wxGlade
}


void XyzFrame::do_layout()
{
    // begin wxGlade: XyzFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    sizer_1->Add(button_1, 0, 0, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(XyzFrame, wxFrame)
    // begin wxGlade: XyzFrame::event_table
    EVT_BUTTON(wxID_ANY, XyzFrame::on_button_1)
    // end wxGlade
END_EVENT_TABLE();


void XyzFrame::on_button_1(wxCommandEvent &event)
{
    wxMessageBox("You hit me!");
    return;
}


// wxGlade: add XyzFrame event handlers

